name: Deploy to megaforce01.com

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REMOTE_HOST: ${{ secrets.SSH_HOST }}
      REMOTE_USER: ${{ secrets.SSH_USER }}
      REMOTE_PORT: ${{ secrets.SSH_PORT }}
      TARGET: ${{ secrets.SSH_TARGET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write private key
        run: |
          echo "${SSH_PRIVATE_KEY}" > key.pem
          chmod 600 key.pem
          ls -l key.pem
          ssh-keygen -lf key.pem || true

      - name: Test SSH connectivity (verbose)
        shell: bash
        run: |
          ssh -vvv \
            -o StrictHostKeyChecking=no \
            -o IdentitiesOnly=yes \
            -o PubkeyAuthentication=yes \
            -o PreferredAuthentications=publickey \
            -p "$REMOTE_PORT" -i key.pem \
            "$REMOTE_USER@$REMOTE_HOST" 'echo OK from server && whoami && pwd'

      - name: Sync files to VPS (rsync)
        shell: bash
        run: |
          export RSYNC_RSH="ssh -p $REMOTE_PORT -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PubkeyAuthentication=yes -o PreferredAuthentications=publickey -i key.pem"
          rsync -az --delete \
            --exclude='.git*' --exclude='.github*' \
            ./ "$REMOTE_USER@$REMOTE_HOST:$TARGET/"

      - name: Cleanup key
        if: always()
        run: |
          shred -u key.pem || rm -f key.pem