name: Deploy to megaforce01.com

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REMOTE_HOST: ${{ secrets.SSH_HOST }}
      REMOTE_USER: ${{ secrets.SSH_USER }}
      REMOTE_PORT: ${{ secrets.SSH_PORT }}
      TARGET: ${{ secrets.SSH_TARGET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test SSH connectivity
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -o IdentitiesOnly=yes \
              -p "$REMOTE_PORT" -i key.pem "$REMOTE_USER@$REMOTE_HOST" 'echo OK from server'

      - name: Sync files to VPS
        uses: easingthemes/ssh-deploy@v4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          TARGET: ${{ secrets.SSH_TARGET }}/
          ARGS: "-az --delete --exclude='.git*' --exclude='.github*'"
          SSH_ARGS: "-o StrictHostKeyChecking=no -o IdentitiesOnly=yes"